In [1]:
import numpy as np

In [3]:
# 요소별로 계산한다 = 브로드케스팅

# 리스트 -> 요소별 계산 불가

print([10,20,30]+[1,2,3])

# np.array -> 요소별 계산 가능

print(np.array([10,20,30])+np.array([1,2,3]))

[10, 20, 30, 1, 2, 3]
[11 22 33]


In [9]:
# 2D array


a14 = np.array([[1,2,3,4]])
print(a14.shape)
print(len(a14))

(1, 4)
1


In [8]:
len(np.array([10,20,30]))

3

In [12]:
print(np.arange(6))
print(np.arange(2,9,2))

[0 1 2 3 4 5]
[2 4 6 8]


In [23]:
ara = np.arange(0,10,2)
ara2 = np.arange(6)
np.flip(ara)

array([8, 6, 4, 2, 0])

In [26]:
# 리스트처럼 계산 하는 법

x = np.concatenate((ara,ara2))
x

array([0, 2, 4, 6, 8, 0, 1, 2, 3, 4, 5])

In [27]:
x[x>3]

array([4, 6, 8, 4, 5])

In [47]:
# 2*3
a23=np.array([[1,2,3],[10,11,12]])
b23=np.array([[4,5,6],[100,110,120]])

In [48]:
a23[a23>2] 
# 결과값은 1차원으로 출력됨

array([ 3, 10, 11, 12])

In [49]:
np.vstack((a23,b23))

array([[  1,   2,   3],
       [ 10,  11,  12],
       [  4,   5,   6],
       [100, 110, 120]])

In [50]:
np.hstack((a23,b23))

array([[  1,   2,   3,   4,   5,   6],
       [ 10,  11,  12, 100, 110, 120]])

In [51]:
c = np.dstack((a23,b23))

In [52]:
c.ndim, c.shape

(3, (2, 3, 2))

In [53]:
b23[1,:] # 인덱스 1인 요소만 추출 -> 1 행만 추출

array([100, 110, 120])

In [56]:
b23=np.array([[4,5,6],[100,110,120]])
c23=b23.copy()
c23[1,2]=400
b23

array([[  4,   5,   6],
       [100, 110, 120]])

In [61]:
c23=b23
c23[1,2]=400
b23

# 이런식으로 복사하면 b23(원본)까지 변경됨 a=b, a=b.view() 같은 의미임
# .copy() 방식으로 복사해야 원본은 변경 안됨

array([[  4,   5,   6],
       [100, 110, 400]])

In [58]:
b23=np.array([[4,5,6],[100,110,120]])
c23=b23.view()
c23[1,2]=400
b23

array([[  4,   5,   6],
       [100, 110, 400]])

In [63]:
# axis 0 은 칼럼 기준 / axis 1 은 행 기준

In [64]:
b23=np.array([[4,5,6],[100,110,120]])
print(b23.sum()) # 요소 전체를 한꺼번에 더하기

print(b23.sum(axis=0)) # 칼럼별로 더하기

print(b23.sum(axis=1)) # 행별로 더하기

345
[104 115 126]
[ 15 330]


In [62]:
# 판다스 카피도 같은 방식인지?????